// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppEigenAutodiff.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// real_wrap_test
autodiff::real real_wrap_test(const double x);
RcppExport SEXP _RcppEigenAutodiff_real_wrap_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(real_wrap_test(x));
    return rcpp_result_gen;
END_RCPP
}
// VectorXreal_wrap_test
autodiff::VectorXreal VectorXreal_wrap_test(const Eigen::VectorXd& x);
RcppExport SEXP _RcppEigenAutodiff_VectorXreal_wrap_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(VectorXreal_wrap_test(x));
    return rcpp_result_gen;
END_RCPP
}
// MatrixXreal_wrap_test
autodiff::MatrixXreal MatrixXreal_wrap_test(const Eigen::MatrixXd& x);
RcppExport SEXP _RcppEigenAutodiff_MatrixXreal_wrap_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(MatrixXreal_wrap_test(x));
    return rcpp_result_gen;
END_RCPP
}
// nr_jac_solve_test
Rcpp::List nr_jac_solve_test();
RcppExport SEXP _RcppEigenAutodiff_nr_jac_solve_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nr_jac_solve_test());
    return rcpp_result_gen;
END_RCPP
}
// nr_test1
Rcpp::List nr_test1();
RcppExport SEXP _RcppEigenAutodiff_nr_test1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nr_test1());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppEigenAutodiff_real_wrap_test", (DL_FUNC) &_RcppEigenAutodiff_real_wrap_test, 1},
    {"_RcppEigenAutodiff_VectorXreal_wrap_test", (DL_FUNC) &_RcppEigenAutodiff_VectorXreal_wrap_test, 1},
    {"_RcppEigenAutodiff_MatrixXreal_wrap_test", (DL_FUNC) &_RcppEigenAutodiff_MatrixXreal_wrap_test, 1},
    {"_RcppEigenAutodiff_nr_jac_solve_test", (DL_FUNC) &_RcppEigenAutodiff_nr_jac_solve_test, 0},
    {"_RcppEigenAutodiff_nr_test1", (DL_FUNC) &_RcppEigenAutodiff_nr_test1, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppEigenAutodiff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
