# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

real_wrap_test <- function(x) {
    .Call(`_RcppEigenAutodiff_real_wrap_test`, x)
}

VectorXreal_wrap_test <- function(x) {
    .Call(`_RcppEigenAutodiff_VectorXreal_wrap_test`, x)
}

MatrixXreal_wrap_test <- function(x) {
    .Call(`_RcppEigenAutodiff_MatrixXreal_wrap_test`, x)
}

nr_jac_solve_test <- function() {
    .Call(`_RcppEigenAutodiff_nr_jac_solve_test`)
}

nr_test1 <- function() {
    .Call(`_RcppEigenAutodiff_nr_test1`)
}

